apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  capacity:
    storage: {{ .Values.pv.size }}
  accessModes:
    {{- range .Values.pv.accessModes }}
    - {{ . }}
    {{- end }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClassName }}
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: {{ .Values.pv.name }}
    volumeAttributes:
      containerName: "tomcat-logs"
      storageAccount: "your-storage-account-name"  # Replace with your actual storage account name

